### ISSUE TITLE
无法发送图片

### ISSUE THREAD

**Issue by yi03** [koishijs/koishi-plugin-wolfram-alpha#1]
现在最新版的koishi安装此插件后，此插件的图片发不出来，只能发出来文字。其他插件可以正常发送图片和文字，只有此插件会出现这个错误。
例如，在群聊和私聊中请求`alpha -f int(sinx)`，都会返回如下内容：
```
Question from xxx: int(sinx)
Indefinite integral:Plots of the integral:Alternate form of the integral:Series expansion of the integral at x = 0:Definite integral over a half-period:Definite integral mean square:
```
并报如下错误：
```
2022-11-28 23:40:26 [W] gocqhttp 警告: 群 图片上传失败: image type error: application/octet-stream
2022-11-28 23:40:26 [W] gocqhttp 警告: 群 图片上传失败: image type error: application/octet-stream
2022-11-28 23:40:26 [W] gocqhttp 警告: 群 图片上传失败: image type error: application/octet-stream
2022-11-28 23:40:26 [W] gocqhttp 警告: 群 图片上传失败: image type error: application/octet-stream
2022-11-28 23:40:26 [W] gocqhttp 警告: 群 图片上传失败: image type error: application/octet-stream
2022-11-28 23:40:26 [W] gocqhttp 警告: 群 图片上传失败: image type error: application/octet-stream
2022-11-28 23:40:26 [W] gocqhttp 警告: 群 图片上传失败: image type error: application/octet-stream
```
如果在沙盒中请求`alpha -f int(sinx)`，则在群聊和私聊中都什么也不会返回，并报如下错误：
```
[W] session TypeError: Cannot read properties of undefined (reading 'startsWith')
        at image (C:\Users\45616\koishi-bot\koishi-app3\node_modules\@koishijs\plugin-sandbox\lib\index.js:46:23)        
        at C:\Users\45616\koishi-bot\koishi-app3\node_modules\@satorijs\core\node_modules\@satorijs\element\lib\index.cjs:278:18
        at Array.forEach (<anonymous>)
        at Function.transform (C:\Users\45616\koishi-bot\koishi-app3\node_modules\@satorijs\core\node_modules\@satorijs\element\lib\index.cjs:273:14)
        at SandboxMessenger.flush (C:\Users\45616\koishi-bot\koishi-app3\node_modules\@koishijs\plugin-sandbox\lib\index.js:44:43)
        at SandboxMessenger.send (C:\Users\45616\koishi-bot\koishi-app3\node_modules\@satorijs\core\lib\index.cjs:403:16)
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async C:\Users\45616\koishi-bot\koishi-app3\node_modules\@koishijs\core\lib\index.cjs:1946:7
 ...
```

**Comment by F1Justin** [comment]
我也有同样的问题
